name: Generate Contribution Snake (Minimal Pro)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Soubhagya-05
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&background=transparent&color_snake=7C3AED&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}